### ISSUE TITLE
Sorting not working correctly

### ISSUE THREAD

**Issue by colethegamer123** [youdroid/home-assistant-couchpotato#10]
Hello Dear youdroid,

First of all I would like to say a big Thank You for your hard work to make this integration!

I have a big movie folder with nearly about 1000 Movie inside. I added the Downloaded-Movies Sensor with your Guide.

```
  - platform: couchpotato
    name: Downloaded movies
    token: !secret TOKEN
    host: 192.168.0.10
    port: 5050
    protocol: 'http'
    state: 'done'
    sort: 'date'
```

The sensor is created but the sorting by date not working correctly. First of all there was a random placement of Movies, after I set sort: 'date' it changed to A-Z Sorting.

Here you can see the actual status:
![image](https://user-images.githubusercontent.com/62310407/93170698-fd14b780-f727-11ea-9218-55c01dcee456.png)

I would like to see what is the newest Downloaded movies, So I can create a notification from Home Assistant if one of my movies what was in the wanted list getting downloaded, so I'll realize OK this movie already out and downloaded to my Plex Server.

If I can provide any other information please let me know.

Thank you,
Best regards,

**Comment by youdroid** [comment]
Hi!

Firstly, thank you I really appreciate your encouragement for this integration. (I was not sure that many people use this App)

I confess to you that I never tested this component with an important film base.
I take note of the fact that you have some sort errors when you sort by date, I will look into this bug.

I find your idea really good to create a notification every time your movie is released and immediately downloaded.

When I find time, I will correct your problem. 
I might come back to you for more info or even to test when I have made the fix.

Thank you for your feedback and have a good day!
We keep in touch,
Best regards,

**Comment by colethegamer123** [comment]
Hello,

Sorry in the meanwhile found out, that notification is not needed because transmission download server has a feature to send notification with home assistant when its downloaded, so you should not include this in couchpotato.

Anyhow Thanks for the fast answer and your hard work, sorting would be really important for some of us im sure 👍 

Best regards,

**Comment by colethegamer123** [comment]
Started to use Radarr
