### ISSUE TITLE
Documentation Update Suggestion.

### ISSUE THREAD

**Issue by micro3x** [youdroid/home-assistant-couchpotato#3]
![CouchApi](https://user-images.githubusercontent.com/6589483/82122213-db67eb80-979a-11ea-8c25-3398744df447.jpg)

I would like to suggest updating the documentation for Api key retrieve to this image... 
I believe it will cause less confusion for users who are less familiar with the browser development tools, like the network tab. :)

**Comment by youdroid** [comment]
Thank you for this wonderful idea. 
I did not know it was possible to retrieve the token from the UI.
You're right, it will be much simpler and easier for everybody !

If you allow me, can I use your own image in my wiki ?
Thank you very much @micro3x :thumbsup:

**Comment by youdroid** [comment]
Thank you, I changed it in the wiki ! 👍
