### ISSUE TITLE
not showing new downloads

### ISSUE THREAD

**Issue by blazem** [youdroid/home-assistant-couchpotato#5]
Hi, gret plugin! relaly keen to have this working. However I have set up a downloaded sensor and it wont show in the card on lovelace, and sensor is showing 'unknown' state in Home Assistant dev states.

my config.yaml:

`  - platform: couchpotato
    token: !SECRET
    state: 'done'
    name: Downloaded Movies
`

Hope you can help

**Comment by youdroid** [comment]
Hi, thank you for your feedback I appreciate it !

Do you have more information in your log about possible errors related to couchpotato sensor which would explain the unknown status ?

**Comment by blazem** [comment]
Yeah very happy to find this integration. 

Here is an error about the sensor in my log file:

> Logger: homeassistant.helpers.entity
Source: c:\users\munden\homeassistant\lib\site-packages\homeassistant\helpers\entity.py:281
First occurred: 12:27:04 AM (945 occurrences)
Last logged: 8:27:58 AM

>Update for sensor.downloaded_movies fails
Traceback (most recent call last):
  File "c:\users\munden\homeassistant\lib\site-packages\homeassistant\helpers\entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "c:\users\munden\homeassistant\lib\site-packages\homeassistant\helpers\entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "C:\Users\Munden\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Munden\AppData\Roaming\.homeassistant\custom_components\couchpotato\sensor.py", line 86, in update
    card_items['airdate'] = datetime.fromtimestamp(movie['info']['release_date']['expires']).strftime(
KeyError: 'release_date'

Any ideas?

**Comment by youdroid** [comment]
Yes thank you, with your log I found your problem. 
Your error is due to an empty release date for this film.
That is why you have this error.

I will fix it in the next few days, and I will publish it in a new release.
I will notify you when it's done !

**Comment by blazem** [comment]
ok cool! Will look forward to it. Thanks a lot

**Comment by youdroid** [comment]
I fixed it in [V1.1.1](https://github.com/youdroid/home-assistant-couchpotato/releases/tag/V1.1.1).

Now all your films should be displayed on your dashboard, without unknown state.

But there may be a display error in the date of the film, if it is not present in couchpotato.
I haven't found a better solution yet....

**Comment by blazem** [comment]
Awesome, confirmed working.

You are right about the date error though. I might see if i can remove that
visibility via athe media card plugin

Do you think there is anyway to list the downloaded movies by recently
downloaded rather than alphabetical?

**Comment by youdroid** [comment]
Hi,

Yes, search on the side of the lovelace configuration. Because the configuration is made for all films in the same way, so if I hide the date it is hidden for all. And as for you, your film has no date, you have an error. In the return of couchpotato, I cannot use any other date ... So it's empty and cannot be displayed correctly.

Yes it is a good idea to also sort by release date. And yes I think it is possible, I will add a parameter in the YAML configuration.
I am currently working on developing services to stop / restart the server, and force the full scan.

I will add all this in a next release, with your feature, count on me !

**Comment by blazem** [comment]
sounds good, thanks for the reply!
